---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart redis
  systemd:
    name: redis-server
    state: restarted

- name: restart pulsar-relay
  systemd:
    name: "{{ pulsar_relay_service_name }}"
    state: restarted
    daemon_reload: true

- name: restart valkey
  systemd:
    name: valkey
    state: restarted
